In [39]:
from pandas import read_csv
from numpy import log
import numpy as np
import pandas as pd
import datetime as datetime

approval_rating_df = pd.read_csv('./data/approval_polllist.csv', parse_dates=["enddate"])
approval_rating_df.head()

,president,subgroup,modeldate,startdate,enddate,pollster,grade,samplesize,population,weight,...,disapprove,adjusted_approve,adjusted_disapprove,multiversions,tracking,url,poll_id,question_id,createddate,timestamp
0,Donald Trump,All polls,10/13/19,1/20/17,2017-01-22,Morning Consult,B-,1992.0,rv,0.944206,...,37.0,44.40140,38.68797,NaN,NaN,http://static.politico.com/9b/13/82a3baf542ae9...,49249,77261,1/23/17,10/13/19 19:10
1,Donald Trump,All polls,10/13/19,1/20/17,2017-01-22,Gallup,B,1500.0,a,0.245429,...,45.0,46.07889,43.38680,NaN,T,http://www.gallup.com/poll/201617/gallup-daily...,49253,77265,1/23/17,10/13/19 19:10
2,Donald Trump,All polls,10/13/19,1/20/17,2017-01-24,Ipsos,B+,1632.0,a,0.224456,...,45.2,42.85173,44.03565,NaN,T,http://polling.reuters.com/#poll/CP3_2/,49426,77599,3/1/17,10/13/19 19:10
3,Donald Trump,All polls,10/13/19,1/21/17,2017-01-23,Gallup,B,1500.0,a,0.226788,...,46.0,46.07889,44.38680,NaN,T,http://www.gallup.com/poll/201617/gallup-daily...,49262,77274,1/24/17,10/13/19 19:10
4,Donald Trump,All polls,10/13/19,1/20/17,2017-01-25,Quinnipiac University,A-,1190.0,rv,1.644662,...,44.0,37.78347,42.75565,NaN,NaN,https://poll.qu.edu/national/release-detail?Re...,49260,77272,1/26/17,10/13/19 19:10

In [40]:
df = pd.read_csv('./data/11-26/daily_plutchik_threshold_5.csv', parse_dates=['month/day'])
df.head()

,month/day,Anger,Disgust,Fear,Joy,Sadness,Surprise,Trust,Anticipation
0,2017-05-07,0.010870,0.021739,0.086957,0.097826,0.032609,0.097826,0.652174,0.000000
1,2017-05-08,0.015785,0.019732,0.071823,0.099448,0.021310,0.105762,0.654301,0.011839
2,2017-05-09,0.018973,0.024554,0.063616,0.093750,0.035714,0.100446,0.652902,0.010045
3,2017-05-10,0.021674,0.033715,0.060205,0.099338,0.031306,0.095725,0.645394,0.012643
4,2017-05-11,0.017838,0.033578,0.055614,0.134313,0.035677,0.123820,0.597062,0.002099

In [41]:
df.tail()

,month/day,Anger,Disgust,Fear,Joy,Sadness,Surprise,Trust,Anticipation
709,2019-04-26,0.012270,0.030675,0.092025,0.153374,0.042945,0.092025,0.576687,0.000000
710,2019-04-27,0.008772,0.026316,0.078947,0.078947,0.017544,0.157895,0.614035,0.017544
711,2019-04-28,0.011364,0.045455,0.079545,0.147727,0.022727,0.136364,0.556818,0.000000
712,2019-04-29,0.005208,0.026042,0.140625,0.072917,0.036458,0.130208,0.583333,0.005208
713,2019-04-30,0.015038,0.022556,0.112782,0.165414,0.022556,0.082707,0.578947,0.000000

In [51]:
start_date = datetime.datetime(2017, 5, 7, 0, 0)
end_date = datetime.datetime(2019, 4, 30, 0, 0)
approval_rating_df = approval_rating_df.loc[(approval_rating_df['enddate'] >= start_date) & (approval_rating_df['enddate'] <= end_date)]

In [52]:
you_gov_df = approval_rating_df.loc[(approval_rating_df['pollster'] == 'YouGov') & (approval_rating_df['population'] == 'a')]

In [53]:
len(you_gov_df)

918

In [54]:
you_gov_df.head()

,president,subgroup,modeldate,startdate,enddate,pollster,grade,samplesize,population,weight,...,disapprove,adjusted_approve,adjusted_disapprove,multiversions,tracking,url,poll_id,question_id,createddate,timestamp
411,Donald Trump,All polls,10/13/19,5/6/17,2017-05-09,YouGov,B,1500.0,a,0.910478,...,51.0,41.88512,53.38865,NaN,NaN,http://d25d2506sfb94s.cloudfront.net/cumulus_u...,49713,78054,5/10/17,10/13/19 19:10
437,Donald Trump,All polls,10/13/19,5/13/17,2017-05-16,YouGov,B,1500.0,a,0.911696,...,51.0,39.88512,53.38865,NaN,NaN,https://d25d2506sfb94s.cloudfront.net/cumulus_...,49739,78096,5/17/17,10/13/19 19:10
471,Donald Trump,All polls,10/13/19,5/20/17,2017-05-23,YouGov,B,1500.0,a,0.911696,...,51.0,39.88512,53.38865,NaN,NaN,http://d25d2506sfb94s.cloudfront.net/cumulus_u...,49764,78138,5/24/17,10/13/19 19:10
491,Donald Trump,All polls,10/13/19,5/27/17,2017-05-30,YouGov,B,1500.0,a,0.911696,...,51.0,38.88512,53.38865,NaN,NaN,http://d25d2506sfb94s.cloudfront.net/cumulus_u...,49801,78244,5/31/17,10/13/19 19:10
520,Donald Trump,All polls,10/13/19,6/4/17,2017-06-06,YouGov,B,1500.0,a,0.912927,...,54.0,38.88512,56.38865,NaN,NaN,http://d25d2506sfb94s.cloudfront.net/cumulus_u...,49825,78288,6/7/17,10/13/19 19:10

In [77]:
def find_longest_contiguous(df):
    max_length = 0
    for index, row in df.iterrows():
        curr = 0
        start_date = row['enddate']
        curr_date = start_date
        new_df = df.loc[df['enddate'] > start_date]
        for index, nested_row in new_df.iterrows():
            diff = (nested_row['enddate']-curr_date).days
            if diff != 1:
                break
                
            curr += 1
            if curr > max_length:
                max_length = curr
                max_start_date = start_date
                max_end_date = curr_date
            curr_date += datetime.timedelta(days=1)
    print("found max length of ", max_length, " starting at ", max_start_date, " ending at ", max_end_date)

In [78]:
find_longest_contiguous(you_gov_df)

found max length of  10  starting at  2018-07-24 00:00:00  ending at  2018-08-02 00:00:00

In [79]:
gallup_df = approval_rating_df.loc[(approval_rating_df['pollster'] == 'Gallup') & (approval_rating_df['subgroup'] == 'All polls')]
find_longest_contiguous(gallup_df)

found max length of  132  starting at  2017-07-13 00:00:00  ending at  2017-11-21 00:00:00

In [80]:
morning_consult_df = approval_rating_df.loc[(approval_rating_df['pollster'] == 'Morning Consult')]
find_longest_contiguous(morning_consult_df)

found max length of  2  starting at  2018-01-19 00:00:00  ending at  2018-01-20 00:00:00

In [81]:
ipsos_df = approval_rating_df.loc[(approval_rating_df['pollster'] == 'Ipsos')]
find_longest_contiguous(ipsos_df)

found max length of  172  starting at  2017-07-12 00:00:00  ending at  2017-12-30 00:00:00